.class public Lcom/android/settings/Settings;
.super Lcom/android/settings/SettingsActivity;
.source "Settings.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/android/settings/Settings$AccessibilityDaltonizerSettingsActivity;,
        Lcom/android/settings/Settings$AccessibilitySettingsActivity;,
        Lcom/android/settings/Settings$AccountSettingsActivity;,
        Lcom/android/settings/Settings$AccountSyncSettingsActivity;,
        Lcom/android/settings/Settings$AdvancedAppsActivity;,
        Lcom/android/settings/Settings$AdvancedWifiSettingsActivity;,
        Lcom/android/settings/Settings$AllApplicationsActivity;,
        Lcom/android/settings/Settings$AndroidBeamSettingsActivity;,
        Lcom/android/settings/Settings$ApnEditorActivity;,
        Lcom/android/settings/Settings$ApnSettingsActivity;,
        Lcom/android/settings/Settings$AppDrawOverlaySettingsActivity;,
        Lcom/android/settings/Settings$AppMemoryUsageActivity;,
        Lcom/android/settings/Settings$AppNotificationSettingsActivity;,
        Lcom/android/settings/Settings$AppOpsSummaryActivity;,
        Lcom/android/settings/Settings$AppWriteSettingsActivity;,
        Lcom/android/settings/Settings$AutomaticStorageManagerSettingsActivity;,
        Lcom/android/settings/Settings$AvailableVirtualKeyboardActivity;,
        Lcom/android/settings/Settings$BackgroundCheckSummaryActivity;,
        Lcom/android/settings/Settings$BatterySaverSettingsActivity;,
        Lcom/android/settings/Settings$BluetoothSettingsActivity;,
        Lcom/android/settings/Settings$CaptioningSettingsActivity;,
        Lcom/android/settings/Settings$ChooseAccountActivity;,
        Lcom/android/settings/Settings$ConfigureNotificationSettingsActivity;,
        Lcom/android/settings/Settings$CryptKeeperSettingsActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryActivity;,
        Lcom/android/settings/Settings$DateTimeSettingsActivity;,
        Lcom/android/settings/Settings$DevelopmentSettingsActivity;,
        Lcom/android/settings/Settings$DeviceAdminSettingsActivity;,
        Lcom/android/settings/Settings$DeviceInfoSettingsActivity;,
        Lcom/android/settings/Settings$DeviceSettings;,
        Lcom/android/settings/Settings$DisplaySettingsActivity;,
        Lcom/android/settings/Settings$DreamSettingsActivity;,
        Lcom/android/settings/Settings$FingerprintEnrollSuggestionActivity;,
        Lcom/android/settings/Settings$FingerprintSuggestionActivity;,
        Lcom/android/settings/Settings$GestureSettingsActivity;,
        Lcom/android/settings/Settings$HighPowerApplicationsActivity;,
        Lcom/android/settings/Settings$HomeSettingsActivity;,
        Lcom/android/settings/Settings$IccLockSettingsActivity;,
        Lcom/android/settings/Settings$ImeiInformationActivity;,
        Lcom/android/settings/Settings$InputMethodAndLanguageSettingsActivity;,
        Lcom/android/settings/Settings$KeyboardLayoutPickerActivity;,
        Lcom/android/settings/Settings$LocalePickerActivity;,
        Lcom/android/settings/Settings$LocationSettingsActivity;,
        Lcom/android/settings/Settings$ManageApplicationsActivity;,
        Lcom/android/settings/Settings$ManageAssistActivity;,
        Lcom/android/settings/Settings$ManageDomainUrlsActivity;,
        Lcom/android/settings/Settings$MemorySettingsActivity;,
        Lcom/android/settings/Settings$NightDisplaySettingsActivity;,
        Lcom/android/settings/Settings$NotificationAccessSettingsActivity;,
        Lcom/android/settings/Settings$NotificationAppListActivity;,
        Lcom/android/settings/Settings$NotificationStationActivity;,
        Lcom/android/settings/Settings$OtherSoundSettingsActivity;,
        Lcom/android/settings/Settings$OverlaySettingsActivity;,
        Lcom/android/settings/Settings$PaymentSettingsActivity;,
        Lcom/android/settings/Settings$PersonalSettings;,
        Lcom/android/settings/Settings$PhysicalKeyboardActivity;,
        Lcom/android/settings/Settings$PowerUsageSummaryActivity;,
        Lcom/android/settings/Settings$PrintJobSettingsActivity;,
        Lcom/android/settings/Settings$PrintSettingsActivity;,
        Lcom/android/settings/Settings$PrivacySettingsActivity;,
        Lcom/android/settings/Settings$PrivateVolumeForgetActivity;,
        Lcom/android/settings/Settings$PrivateVolumeSettingsActivity;,
        Lcom/android/settings/Settings$PublicVolumeSettingsActivity;,
        Lcom/android/settings/Settings$RoamingSettingsActivity;,
        Lcom/android/settings/Settings$RunningServicesActivity;,
        Lcom/android/settings/Settings$SavedAccessPointsSettingsActivity;,
        Lcom/android/settings/Settings$ScreenLockSuggestionActivity;,
        Lcom/android/settings/Settings$SecuritySettingsActivity;,
        Lcom/android/settings/Settings$SimSettingsActivity;,
        Lcom/android/settings/Settings$SimStatusActivity;,
        Lcom/android/settings/Settings$SoundSettingsActivity;,
        Lcom/android/settings/Settings$SpellCheckersSettingsActivity;,
        Lcom/android/settings/Settings$StatusActivity;,
        Lcom/android/settings/Settings$StorageSettingsActivity;,
        Lcom/android/settings/Settings$StorageUseActivity;,
        Lcom/android/settings/Settings$SystemSettings;,
        Lcom/android/settings/Settings$TestingSettingsActivity;,
        Lcom/android/settings/Settings$TetherSettingsActivity;,
        Lcom/android/settings/Settings$TextToSpeechSettingsActivity;,
        Lcom/android/settings/Settings$TimerSwitchSettingsActivity;,
        Lcom/android/settings/Settings$TopLevelSettings;,
        Lcom/android/settings/Settings$TrustedCredentialsSettingsActivity;,
        Lcom/android/settings/Settings$UsageAccessSettingsActivity;,
        Lcom/android/settings/Settings$UserDictionarySettingsActivity;,
        Lcom/android/settings/Settings$UserSettingsActivity;,
        Lcom/android/settings/Settings$VpnSettingsActivity;,
        Lcom/android/settings/Settings$VrListenersSettingsActivity;,
        Lcom/android/settings/Settings$WallpaperSettingsActivity;,
        Lcom/android/settings/Settings$WifiAPITestActivity;,
        Lcom/android/settings/Settings$WifiCallingSettingsActivity;,
        Lcom/android/settings/Settings$WifiCallingSuggestionActivity;,
        Lcom/android/settings/Settings$WifiDisplaySettingsActivity;,
        Lcom/android/settings/Settings$WifiInfoActivity;,
        Lcom/android/settings/Settings$WifiP2pSettingsActivity;,
        Lcom/android/settings/Settings$WifiSettingsActivity;,
        Lcom/android/settings/Settings$WirelessSettings;,
        Lcom/android/settings/Settings$WirelessSettingsActivity;,
        Lcom/android/settings/Settings$WriteSettingsActivity;,
        Lcom/android/settings/Settings$ZenAccessSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeAutomationSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeAutomationSuggestionActivity;,
        Lcom/android/settings/Settings$ZenModeEventRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeExternalRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModePrioritySettingsActivity;,
        Lcom/android/settings/Settings$ZenModeScheduleRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeVisualInterruptionSettingsActivity;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 27
    invoke-direct {p0}, Lcom/android/settings/SettingsActivity;-><init>()V

    return-void
.end method
